sudo: false
language: node_js
notifications:
  email:
    on_success: never
    on_failure: never

node_js:
  - "stable"

before_install:
  - npm install
  - npm install coveralls

script:
  - npm run test

after_success:
  - npm run test:coverage
  - npm run coveralls