sudo: false
language: node_js
notifications:
  email:
    on_success: never
    on_failure: never

node_js:
  - "stable"

before_install:
  - npm install -g npm
  - npm install coveralls

script:
  - npm run rest

after_success:
  - npm run coveralls